# Global Constants
WINDOW_WIDTH, WINDOW_HEIGHT = 800, 600
SHIP_WIDTH, SHIP_HEIGHT = 60, 20
PROJECTILE_RADIUS = 2
ENEMY_WIDTH, ENEMY_HEIGHT = 60, 20

# Speed
SHIP_SPEED = 10
PROJECTILE_SPEED = 5
ENEMY_SPEED = 4
ENEMY_PROJECTILE_SPEED = 3

# Enemy firing probability
ENEMY_FIRE_PROBABILITY = 0.0075  # 0.75% chance to fire each frame
