# Constantes globales
WINDOW_WIDTH, WINDOW_HEIGHT = 800, 600
VAISSEAU_WIDTH, VAISSEAU_HEIGHT = 60, 20
PROJECTILE_RADIUS = 2
ENNEMI_WIDTH, ENNEMI_HEIGHT = 60, 20

# Vitesse
VITESSE_VAISSEAU = 10
VITESSE_PROJECTILES = 5
VITESSE_ENNEMI = 4
VITESSE_PROJECTILES_ENNEMI = 3

# Probabilité de tir des ennemis
PROBA_TIR_ENNEMI = 0.0075  # 0.75% de chance de tirer à chaque frame